# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CardConnection.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 220)
        self.updateButton = QtWidgets.QPushButton(Form)
        self.updateButton.setGeometry(QtCore.QRect(320, 48, 110, 33))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.updateButton.setFont(font)
        self.updateButton.setIconSize(QtCore.QSize(22, 22))
        self.updateButton.setFlat(False)
        self.updateButton.setObjectName("updateButton")
        self.readersList = QtWidgets.QComboBox(Form)
        self.readersList.setGeometry(QtCore.QRect(10, 50, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.readersList.setFont(font)
        self.readersList.setStatusTip("")
        self.readersList.setCurrentText("")
        self.readersList.setDuplicatesEnabled(False)
        self.readersList.setObjectName("readersList")
        self.cardTypesList = QtWidgets.QComboBox(Form)
        self.cardTypesList.setEnabled(True)
        self.cardTypesList.setGeometry(QtCore.QRect(10, 125, 291, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cardTypesList.setFont(font)
        self.cardTypesList.setStatusTip("")
        self.cardTypesList.setCurrentText("")
        self.cardTypesList.setDuplicatesEnabled(False)
        self.cardTypesList.setObjectName("cardTypesList")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 194, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.nextButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.nextButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextButton.setFont(font)
        self.nextButton.setAutoDefault(False)
        self.nextButton.setDefault(False)
        self.nextButton.setFlat(False)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.exitButton = QtWidgets.QPushButton(Form)
        self.exitButton.setGeometry(QtCore.QRect(320, 170, 110, 33))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 85, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        self.cancelButton.pressed.connect(Form.cancelButtonPressed) # type: ignore
        self.nextButton.pressed.connect(Form.nextButtonPressed) # type: ignore
        self.exitButton.pressed.connect(Form.exitButtonPressed) # type: ignore
        self.updateButton.pressed.connect(Form.updateButtonPressed) # type: ignore
        self.readersList.currentIndexChanged['int'].connect(Form.readersListIndexChanged) # type: ignore
        self.cardTypesList.currentIndexChanged['int'].connect(Form.cardTypesListIndexChanged) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SPMC"))
        self.updateButton.setToolTip(_translate("Form", "Update cardreaders list"))
        self.updateButton.setText(_translate("Form", "update"))
        self.cancelButton.setText(_translate("Form", "cancel"))
        self.nextButton.setText(_translate("Form", "next"))
        self.exitButton.setText(_translate("Form", "exit"))
        self.label.setText(_translate("Form", "Cardreader:"))
        self.label_2.setText(_translate("Form", "Cardtype:"))
