# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CardConnection.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(330, 150)
        self.updateButton = QtWidgets.QPushButton(Form)
        self.updateButton.setGeometry(QtCore.QRect(220, 20, 91, 30))
        self.updateButton.setIconSize(QtCore.QSize(22, 22))
        self.updateButton.setFlat(False)
        self.updateButton.setObjectName("updateButton")
        self.readersList = QtWidgets.QComboBox(Form)
        self.readersList.setGeometry(QtCore.QRect(10, 20, 200, 28))
        self.readersList.setStatusTip("")
        self.readersList.setDuplicatesEnabled(False)
        self.readersList.setObjectName("readersList")
        self.readersList.addItem("")
        self.cardTypesList = QtWidgets.QComboBox(Form)
        self.cardTypesList.setEnabled(False)
        self.cardTypesList.setGeometry(QtCore.QRect(10, 60, 200, 28))
        self.cardTypesList.setStatusTip("")
        self.cardTypesList.setDuplicatesEnabled(False)
        self.cardTypesList.setObjectName("cardTypesList")
        self.cardTypesList.addItem("")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 194, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.nextButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.nextButton.setEnabled(False)
        self.nextButton.setAutoDefault(False)
        self.nextButton.setDefault(False)
        self.nextButton.setFlat(False)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.exitButton = QtWidgets.QPushButton(Form)
        self.exitButton.setGeometry(QtCore.QRect(220, 110, 93, 28))
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(Form)
        self.cancelButton.pressed.connect(Form.cancelButtonPressed) # type: ignore
        self.nextButton.pressed.connect(Form.nextButtonPressed) # type: ignore
        self.exitButton.pressed.connect(Form.exitButtonPressed) # type: ignore
        self.updateButton.pressed.connect(Form.updateButtonPressed) # type: ignore
        self.readersList.currentIndexChanged['int'].connect(Form.readersListIndexChanged) # type: ignore
        self.cardTypesList.currentIndexChanged['int'].connect(Form.cardTypesListIndexChanged) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SPMC"))
        self.updateButton.setToolTip(_translate("Form", "Update cardreaders list"))
        self.updateButton.setText(_translate("Form", "update"))
        self.readersList.setCurrentText(_translate("Form", "   <Select cardreader>"))
        self.readersList.setItemText(0, _translate("Form", "   <Select cardreader>"))
        self.cardTypesList.setCurrentText(_translate("Form", "   <Select card type>"))
        self.cardTypesList.setItemText(0, _translate("Form", "   <Select card type>"))
        self.cancelButton.setText(_translate("Form", "cancel"))
        self.nextButton.setText(_translate("Form", "next"))
        self.exitButton.setText(_translate("Form", "exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
