# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EncryptSeedPhrase.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 220)
        self.algorithmsList = QtWidgets.QComboBox(Form)
        self.algorithmsList.setGeometry(QtCore.QRect(210, 10, 230, 30))
        self.algorithmsList.setStatusTip("")
        self.algorithmsList.setCurrentText("")
        self.algorithmsList.setDuplicatesEnabled(False)
        self.algorithmsList.setObjectName("algorithmsList")
        self.contactDataTextEdit = QtWidgets.QPlainTextEdit(Form)
        self.contactDataTextEdit.setGeometry(QtCore.QRect(10, 50, 431, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.contactDataTextEdit.setFont(font)
        self.contactDataTextEdit.setBackgroundVisible(False)
        self.contactDataTextEdit.setObjectName("contactDataTextEdit")
        self.labelCorrect = QtWidgets.QLabel(Form)
        self.labelCorrect.setGeometry(QtCore.QRect(100, 140, 221, 21))
        self.labelCorrect.setText("")
        self.labelCorrect.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCorrect.setObjectName("labelCorrect")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 120, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.passwordEdit = QtWidgets.QLineEdit(Form)
        self.passwordEdit.setGeometry(QtCore.QRect(105, 120, 336, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setEchoMode(QtWidgets.QLineEdit.NoEcho)
        self.passwordEdit.setClearButtonEnabled(True)
        self.passwordEdit.setObjectName("passwordEdit")
        self.exitButton = QtWidgets.QPushButton(Form)
        self.exitButton.setGeometry(QtCore.QRect(350, 180, 93, 33))
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 194, 35))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.encryptButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.encryptButton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.encryptButton.setFont(font)
        self.encryptButton.setAutoDefault(False)
        self.encryptButton.setDefault(False)
        self.encryptButton.setFlat(False)
        self.encryptButton.setObjectName("encryptButton")
        self.horizontalLayout.addWidget(self.encryptButton)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        self.contactDataTextEdit.textChanged.connect(Form.textEditTextChanged) # type: ignore
        self.cancelButton.pressed.connect(Form.cancelButtonPressed) # type: ignore
        self.exitButton.pressed.connect(Form.exitButtonPressed) # type: ignore
        self.encryptButton.pressed.connect(Form.encryptButtonPressed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SPMC"))
        self.contactDataTextEdit.setPlaceholderText(_translate("Form", "If you want, you can enter contact information that will be stored on the card (maximum length can be 20 characters)"))
        self.label.setText(_translate("Form", "Password:"))
        self.passwordEdit.setPlaceholderText(_translate("Form", "(empty)"))
        self.exitButton.setText(_translate("Form", "exit"))
        self.cancelButton.setText(_translate("Form", "cancel"))
        self.encryptButton.setText(_translate("Form", "encrypt"))
        self.label_2.setText(_translate("Form", "Encryption algorithm:"))
